name: Application Pipeline Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read
  actions: read
  checks: write      

jobs:
  install_flutter_and_java:
    name: Install Flutter and Java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: List directory
        run: ls -a          

      - name: Check Flutter version
        run: |
          flutter --version

      - name: Get project dependencies        
        run: |
          flutter pub get

  test_and_analyze:
    needs: install_flutter_and_java
    runs-on: ubuntu-latest
    name: Test and Analyze
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Run tests and analysis
        run: |
          flutter test && analysis
        
      - name: Compile test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: test-results
          name: Flutter tests 
          path: 'reports/test-results.json'
          reporter: flutter-json

      - name: Handle failures
        if: failure()
        run: |
          exit 1
