name: Main Merge

on:
  push:
      branches:
          - main
      
permissions:
  contents: write
  packages: write

jobs:
    build_windows:
        name: Build Windows artefacts
        runs-on: windows-latest
        defaults:
            run:
              working-directory: src
        
        steps:
            - name: ⬇️ Check-out repository
              uses: actions/checkout@v4

            - name: 🐦 Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true

            - name: 🔍 Get project dependencies        
              run: flutter clean && flutter pub get    
            
            - name: Generate intermediates
              run: flutter pub run build_runner build --delete-conflicting-outputs

            - name: Enable windows build
              run: flutter config --enable-windows-desktop

            - name: Build artifacts
              run: flutter build windows --release

            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: WizardingWorld-release-windows.zip
                directory: ${{github.workspace}}/src/build/windows/x64/runner/Release/

            - name: Windows Release
              uses: softprops/action-gh-release@v1              
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: 'v0.0.1'
                prerelease: false
                draft: false
                files: ${{github.workspace}}\src\build\windows\x64\runner\Release\WizardingWorld-release-windows.zip
                