name: Main Merge

on:
    push:
        branches:
            - main

jobs:
    build_windows:
        name: Build Windows artefacts
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: src
        
        steps:
            - name: ⬇️ Check-out repository
              uses: actions/checkout@v4

            - name: 🐦 Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true

            - name: 🔍 Get project dependencies        
              run: flutter clean && flutter pub get    
            
            - name: Generate intermediates
              run: flutter pub run build_runner build --delete-conflicting-outputs

            - name: Enable windows build
              run: flutter config --enable-windows-desktop

            - name: Build artifacts
              run: flutter build windows --release

            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: WizardingWorld-${{github.ref_name}}-windows.zip
                directory: ${{github.workspace}}/src/build/windows/runner/Release

            - name: Windows Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files:
                    ${{github.workspace}}/src/build/windows/runner/Release/WizardingWorld-${{github.ref_name}}-windows.zip